export const STAGE = "COMMIT" as const;

export const COMMIT_RULES = [
  "PARSE_FAILED",

  "PROPOSAL_ID_MISMATCH_REVALIDATION",
  "PROPOSAL_ID_MISMATCH_EFFECTS_LOG",

  "OUTCOME_UNSUPPORTED",

  "PARTIAL_EMPTY_ALLOWLIST_COMMITS_NOTHING",
  "PARTIAL_ALLOWLIST_HAS_UNKNOWN_IDS",
  "PARTIAL_COMMIT_USE_ALLOWLIST",

  "FULL_COMMIT_ALL_PROVISIONAL_EFFECTS",
  "FULL_IGNORES_ALLOWLIST",
] as const;

export const TRUST_PROVISIONAL = "PROVISIONAL" as const;
export const TRUST_COMMMITED = "COMMITTED" as const;
